---
title: "Forecasting Crude Oil Prices"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(plotly)
```


```{r forecast, echo=FALSE, fig.height=7, fig.width=12, message=FALSE, warning=FALSE, paged.print=FALSE}

ts_forecast<- readRDS('/Users/masonveilleux/Dropbox/forecasting_projects/oil_price/oil_price_forecasting/latest_ans_price_dor.rds')



x <- list(
  title = "Year")
y <- list(
  title = " $/barrel")

p <- plot_ly(data =ts_forecast,x= ~date,line =list(colorscale = 'Accent')) %>%
  add_lines(x = ts_forecast$date, y = ts_forecast$ts_oil, name = "ANS Monthly Average",hovertemplate = paste0("$/barrel: ",ts_forecast$ts_oil)) %>% 
  
  add_lines(x = ts_forecast$date, y = ts_forecast$oilfit2.mean  ,name = "No-change", line = list(dash = 'dot'),hovertemplate = paste0("$/barrel: ",ts_forecast$oilfit2.mean)) %>%
  
  add_lines(x = ts_forecast$date, y = ts_forecast$oilfit4.mean , name = "Drift No-change", line = list(dash = 'dot'),hovertemplate = paste0("$/barrel: ",ts_forecast$oilfit4.mean)) %>%
  
  add_lines(x = ts_forecast$date, y = ts_forecast$ets.mean , name = "ETS", line = list(dash = 'dot'),hovertemplate = paste0("$/barrel: ",ts_forecast$ets.mean)) %>%
  
  add_lines(x = ts_forecast$date, y = ts_forecast$arima.mean , name = "ARIMA(1,1,0)", line = list(dash = 'dot'),hovertemplate = paste0("$/barrel: ",ts_forecast$arima.mean)) %>% 
  
  add_lines(x = ts_forecast$date, y = ts_forecast$nymex_fit.mean , name = "Avg. Cushing Futures (ARIMA(1,1,0))", line = list(dash = 'dot'),hovertemplate = paste0("$/barrel: ",ts_forecast$nymex_fit.mean)) %>% 
  
  layout(hovermode = "x unified",
         xaxis = list(title = "Year", rangeslider = list(type = "date")), 
         yaxis = list(title = "$/barrel"),
         title = 'ANS Price per Barrel Forecast')

p


```




